name: publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: check for .only
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm install --save-dev stop-only
      - name: run stop-only 
        run: stop-only --folder tests --folder bin